### ISSUE TITLE
Change receptors on parasites to diamond shapes

### ISSUE THREAD

**Issue by amberfoam** [fo-am/roysoc-malaria#4]

**Comment by amberfoam** [comment]
Yellow one needs to be diamond shaped.
All could be diamond shaped, or other colours could also be different shapes (might be a bit confusing, but also might be helpful for colour-blindness, though I have already checked the colours are basically ok for this)

**Comment by nebogeo** [comment]
Trying it with all circles as that seems clearest. One option is to have them all back in, and add shape labels to the bottles as an additional cue.
